# Base configuration for SDXL training.
# This file will be dynamically modified by the training script.

async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 50 # Increased epochs for longer potential training
gradient_accumulation_steps = 1
gradient_checkpointing = true
huggingface_repo_visibility = "public"
learning_rate = 0.00001
loss_type = "l2"
lr_scheduler = "constant"
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
min_bucket_reso = 256
min_snr_gamma = 5
mixed_precision = "bf16"
network_alpha = 16
network_dim = 32
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Original"
optimizer_type = "AdamW8Bit"
output_name = "last"
pretrained_model_name_or_path = "" # To be filled by script
prior_loss_weight = 1
resolution = "1024,1024"
save_every_n_epochs = 0 # Disable periodic checkpointing, only save the final model
save_model_as = "safetensors"
save_precision = "bf16"
scale_weight_norms = 5
text_encoder_lr = 0.00001
train_batch_size = 4
train_data_dir = "" # To be filled by script
unet_lr = 0.00001
xformers = true
output_dir = "" # To be filled by script 