# Base configuration for Flux training.
# This file will be dynamically modified by the training script.

ae = "/app/flux/ae.safetensors"
apply_t5_attn_mask = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_l = "/app/flux/clip_l.safetensors"
discrete_flow_shift = 3.1582
dynamo_backend = "no"
epoch = 100 # Increased epochs for longer potential training
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1.0
highvram = true
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
huggingface_repo_visibility = "public"
loss_type = "l2"
lr_scheduler = "constant"
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
mem_eff_save = true
min_bucket_reso = 256
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 128
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all", "train_t5xxl=True",]
network_dim = 128
network_module = "networks.lora_flux"
noise_offset_type = "Original"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False", "weight_decay=0.01",]
optimizer_type = "Adafactor"
output_name = "last"
pretrained_model_name_or_path = "" # To be filled by script
prior_loss_weight = 1
resolution = "1024,1024"
save_every_n_epochs = 0 # Disable periodic checkpointing, only save the final model
save_model_as = "safetensors"
save_precision = "float"
seed = 1
t5xxl = "/app/flux/t5xxl_fp16.safetensors"
t5xxl_max_token_length = 512
text_encoder_lr = [ 5e-5, 5e-5,]
timestep_sampling = "sigmoid"
train_batch_size = 1
train_data_dir = "" # To be filled by script
unet_lr = 5e-5
vae_batch_size = 4
xformers = true
output_dir = "" # To be filled by script 